name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Git submodules
      run: git submodule update --init --recursive

    - name: Test
      run: bash scripts/test.sh

    - name: Test the examples
      run: |
        cd examples
        mkdir build
        cd build
        cmake ..
        cmake --build .
